<?xml version="1.0"?>
<project name="Auto Screenshot">
	<taskdef resource="net/sf/antcontrib/antcontrib.properties"/>

	<!-- Properties: -->
	<!-- <property file="local.properties"/> -->
	<loadproperties srcfile="local.properties" encoding="UTF-8">
		<filterchain>
			<escapeunicode />
		</filterchain>
	</loadproperties>
	
	
	<condition property="os_family" value="Windows">
		<os family="windows" />
	</condition>
	<condition property="os_family" value="Linux">
		<os family="unix" />
	</condition>
	
	<condition property="is_windows">
		<os family="windows"/>
	</condition>
	<condition property="is_linux">
		<os family="unix"/>
	</condition>
	
	<!-- #ProgramVersion=$(grep -Po '\<StringTable.+ ProductVersion="\K[0-9\.]+' AutoScreenshot.lpi) -->
	<exec executable="git" outputproperty="version" failifexecutionfails="false">
		<arg value="describe"/>
		<arg value="--dirty"/>
		<!-- <arg value=" - - long"/> -->
	</exec>
	<property name="version" value="unknown" /><!--на случай если гит отсутвтует и предыдущая команда завершилась с ошибкой-->
	
	<!--<property name="build_dir" location="build"/>-->
	<property name="build_dir" location="build/files"/>
	<property name="build_x86_dir" location="build/x86_files"/>
	<property name="build_x64_dir" location="build/x64_files"/>
	<property name="release_dir" location="build/releases/${version}"/>
	<!--<property name="zip_dir" location="build/zip"/>-->
	<property name="test_dir" location="Test"/>
	<property name="temp_dir" location="build/temp"/>
	
	<condition property="executable" value="AutoScreenshot.exe">
		<os family="windows" />
	</condition>
	<condition property="executable" value="AutoScreenshot">
		<os family="unix" />
	</condition>
	
	<property name="build_mode" value="Release"/>
	
	<condition property="lazbuild_path" value="${lazarus_dir}/lazbuild.exe">
		<os family="windows" />
	</condition>
	<condition property="lazbuild_path" value="/home/user/fpcupdeluxe/lazarus/lazbuild">
		<os family="unix" />
	</condition>
	
	
	<!-- Targets: -->
	<target name="clean">
		<delete dir="${build_dir}"/>
		<!--<delete dir="${build_x86_dir}"/>
		<delete dir="${build_x64_dir}"/>-->
		<delete dir="lib"/>
		<delete file="${executable}"/>
		<delete dir="${temp_dir}"/>
	</target>
	
	<target name="init" depends="clean">
		<!-- <echoproperties/> -->
		<echo>Program version: ${version}</echo>
		<mkdir dir="${build_dir}"/>
		<mkdir dir="${release_dir}"/>
		<!-- <mkdir dir="${zip_dir}"/> -->
		<mkdir dir="${temp_dir}"/>
	</target>
	
	<target name="build" depends="init" description="Compile executable">
		<echo>Compile executable</echo>
		
		<if>
			<equals arg1="${arch}" arg2="x86" />
			<then>
				<var name="a" value="i386"/>
			</then>
		</if>
		<if>
			<equals arg1="${arch}" arg2="x64" />
			<then>
				<var name="a" value="x86_64"/>
			</then>
		</if>
		
		<exec executable="${lazbuild_path}" failifexecutionfails="true" failonerror="true">
			<arg value="--build-mode=${build_mode}"/>
			<!--<arg value="- - verbose"/>-->
			<arg value="--cpu=${a}"/>
			<arg value="AutoScreenshot.lpi"/>
		</exec>
	</target>
	
	<target name="build_tests">
		<echo>Compile tests</echo>
		
		<if>
			<equals arg1="${arch}" arg2="x86" />
			<then>
				<var name="a" value="i386"/>
			</then>
		</if>
		<if>
			<equals arg1="${arch}" arg2="x64" />
			<then>
				<var name="a" value="x86_64"/>
			</then>
		</if>
		
		<exec executable="${lazbuild_path}" dir="${test_dir}" failifexecutionfails="true" failonerror="true">
			<arg value="--cpu=${a}"/>
			<arg value="AutoScreenshotTest.lpi"/>
		</exec>
	</target>
	
	<target name="tests" depends="build_tests" description="Run all unit tests">
		<echo>Run tests</echo>
		<condition property="test_executable_filename" value="AutoScreenshotTest.exe">
			<os family="windows" />
		</condition>
		<condition property="test_executable_filename" value="AutoScreenshotTest">
			<os family="unix" />
		</condition>
		<!-- <exec executable="${test_executable_filename}" dir="${test_dir}" failonerror="true"> -->
		<exec executable="${test_dir}/${test_executable_filename}" failonerror="true">
			<arg value="--all"/>
			<arg value="--format=plain"/>
		</exec>
	</target>
	
	<target name="zip" depends="download_dlls_once, build, tests" description="Pack all to ZIP archive">
		<copy file="${executable}" todir="${build_dir}" preservelastmodified="true"/>
		
		<if>
			<equals arg1="${os_family}" arg2="Windows" />
			<then>
				<if>
					<equals arg1="${arch}" arg2="x86"/>
					<then>
						<var name="dll_dir" value="${build_x86_dir}" />
					</then>
				</if>
				<if>
					<equals arg1="${arch}" arg2="x64"/>
					<then>
						<var name="dll_dir" value="${build_x64_dir}" />
					</then>
				</if>
				
				<copy file="${dll_dir}/libeay32.dll" todir="${build_dir}" preservelastmodified="true"/>
				<copy file="${dll_dir}/ssleay32.dll" todir="${build_dir}" preservelastmodified="true"/>
				<copy file="${dll_dir}/sqlite3.dll" todir="${build_dir}" preservelastmodified="true"/>
				
				<if>
					<equals arg1="${arch}" arg2="x86" />
					<then>
						<copy file="${dll_dir}/libwebp32.dll" todir="${build_dir}" preservelastmodified="true"/>
					</then>
				</if>
				<if>
					<equals arg1="${arch}" arg2="x64" />
					<then>
						<copy file="${dll_dir}/libwebp64.dll" todir="${build_dir}" preservelastmodified="true"/>
					</then>
				</if>
				
				<copy file="${dll_dir}/libaom.dll" todir="${build_dir}" preservelastmodified="true"/>
				<copy file="${dll_dir}/libavif.dll" todir="${build_dir}" preservelastmodified="true"/>
				<copy file="${dll_dir}/libdav1d.dll" todir="${build_dir}" preservelastmodified="true"/>
				
				<if>
					<equals arg1="${arch}" arg2="x86" />
					<then>
						<copy file="${dll_dir}/libgcc_s_dw2-1.dll" todir="${build_dir}" preservelastmodified="true"/>
					</then>
				</if>
				<if>
					<equals arg1="${arch}" arg2="x64" />
					<then>
						<copy file="${dll_dir}/libgcc_s_seh-1.dll" todir="${build_dir}" preservelastmodified="true"/>
					</then>
				</if>
				
				<copy file="${dll_dir}/libwinpthread-1.dll" todir="${build_dir}" preservelastmodified="true"/>
				<copy file="${dll_dir}/rav1e.dll" todir="${build_dir}" preservelastmodified="true"/>
				<copy file="${dll_dir}/libjpeg-8.dll" todir="${build_dir}" preservelastmodified="true" />
				<if>
					<equals arg1="${arch}" arg2="x64" />
					<then>
						<copy file="${dll_dir}/libsharpyuv-0.dll" todir="${build_dir}" preservelastmodified="true"/>
						<copy file="${dll_dir}/libSvtAv1Dec.dll" todir="${build_dir}" preservelastmodified="true"/>
						<copy file="${dll_dir}/libSvtAv1Enc.dll" todir="${build_dir}" preservelastmodified="true"/>
					</then>
				</if>
				<copy file="${dll_dir}/libstdc++-6.dll" todir="${build_dir}" preservelastmodified="true" />
				<copy file="${dll_dir}/libyuv.dll" todir="${build_dir}" preservelastmodified="true" />
			</then>
		</if>
		<mkdir dir="${build_dir}/lang"/>
		<copy todir="${build_dir}/lang" preservelastmodified="true">
			<fileset dir="lang" includes="*.ini"/>
		</copy>
		<copy todir="${build_dir}/sounds" preservelastmodified="true">
			<fileset dir="sounds" includes="*.wav"/>
		</copy>
		
		<copy file="LICENSE.txt" todir="${build_dir}" preservelastmodified="true"/>
		
		<copy todir="${temp_dir}/AutoScreenshot_${version}" preservelastmodified="true">
			<fileset dir="${build_dir}" includes="**"/>
		</copy>
		
		<zip basedir="${temp_dir}" destfile="${release_dir}/AutoScreenshot_${version}_${os_family}_${arch}_portable.zip" level="9"/>
	</target>
	
	<!--<target name="installer" depends="download_dlls_once, build, tests" description="Make installer file (Windows only)" if="is_windows">-->
	<target name="installer" depends="download_dlls_once" description="Make installer file (Windows only)" if="is_windows">
		<!--<echoproperties/>-->
		<!--<if>
			<os family="windows"/>
			<then>-->
		
				<!-- Prepare files for x86 -->
<!--				<antcall target="download_dlls">
					<param name="arch" value="x86"/>
				</antcall>
				<copy todir="${build_x86_dir}">
					<fileset dir="${basedir}" includes="/*.dll"/>
				</copy>-->
				<antcall target="build">
					<param name="arch" value="x86"/>
				</antcall>
				<copy file="${basedir}/AutoScreenshot.exe" todir="${build_x86_dir}" failonerror="true" />
				
				<!-- Prepare files for x64 -->
<!--				<antcall target="download_dlls">
					<param name="arch" value="x64"/>
				</antcall>
				<copy todir="${build_x64_dir}">
					<fileset dir="${basedir}" includes="/*.dll"/>
				</copy>-->
				<antcall target="build">
					<param name="arch" value="x64"/>
				</antcall>
				<copy file="${basedir}/AutoScreenshot.exe" todir="${build_x64_dir}" failonerror="true" />
		
				<!-- Run Inno Setup script compiling -->
				<exec executable="${inno_setup_dir}/ISCC.exe" failonerror="true">
					<!--<env key="LazarusDir" value="${lazarus_dir}"/>-->
					<arg value="/DMyAppRevision=${version}"/>
					<arg value="setup.iss"/>
				</exec>
			<!--</then>
			<else>
				<fail>Target not supported on this OS</fail>
			</else>
		</if>-->
	</target>
	
	<!--<target name="delete_dlls">
		<delete>
			<fileset dir="${basedir}" includes="/*.dll"/>
		</delete>
	</target>-->
	
	<target name="download_dlls_once" if="is_windows" description="Download DLLs only if needed (Windows only)">
		<!-- x86 -->
		<echo>Check DLLs for x86 ...</echo>
		<if>
			<and>
				<available file="${build_x86_dir}/sqlite3.dll"/>
				<available file="${build_x86_dir}/ssleay32.dll"/>
				<available file="${build_x86_dir}/libeay32.dll"/>
				<available file="${build_x86_dir}/libwebp32.dll"/>
				<available file="${build_x86_dir}/rav1e.dll"/>
				<available file="${build_x86_dir}/libwinpthread-1.dll"/>
				<available file="${build_x86_dir}/libgcc_s_dw2-1.dll"/>
				<available file="${build_x86_dir}/libdav1d.dll"/>
				<available file="${build_x86_dir}/libavif.dll"/>
				<available file="${build_x86_dir}/libaom.dll"/>
				<available file="${build_x86_dir}/libjpeg-8.dll" />
				<available file="${build_x86_dir}/libstdc++-6.dll" />
				<available file="${build_x86_dir}/libyuv.dll" />
			</and>
			<then>
				<echo>Ok!</echo>
			</then>
			<else>
				<echo>Need to download</echo>
				<antcall target="download_dlls">
					<param name="arch" value="x86"/>
				</antcall>
			</else>
		</if>
		
		<!-- x64 -->
		<echo>Check DLLs for x64 ...</echo>
		<if>
			<and>
				<available file="${build_x64_dir}/sqlite3.dll"/>
				<available file="${build_x64_dir}/ssleay32.dll"/>
				<available file="${build_x64_dir}/libeay32.dll"/>
				<available file="${build_x64_dir}/libwebp64.dll"/>
				<available file="${build_x64_dir}/rav1e.dll"/>
				<available file="${build_x64_dir}/libwinpthread-1.dll"/>
				<available file="${build_x64_dir}/libgcc_s_seh-1.dll"/>
				<available file="${build_x64_dir}/libdav1d.dll"/>
				<available file="${build_x64_dir}/libavif.dll"/>
				<available file="${build_x64_dir}/libaom.dll"/>
				<available file="${build_x64_dir}/libjpeg-8.dll" />
				<available file="${build_x64_dir}/libsharpyuv-0.dll" />
				<available file="${build_x64_dir}/libstdc++-6.dll" />
				<available file="${build_x64_dir}/libSvtAv1Dec.dll" />
				<available file="${build_x64_dir}/libSvtAv1Enc.dll" />
				<available file="${build_x64_dir}/libyuv.dll" />
			</and>
			<then>
				<echo>Ok!</echo>
			</then>
			<else>
				<echo>Need to download</echo>
				<antcall target="download_dlls">
					<param name="arch" value="x64"/>
				</antcall>
			</else>
		</if>
	</target>
	
	<!--<target name="download_dlls" depends="delete_dlls" description="Download all required dlls to project main directory (Windows only)" if="is_windows">-->
	<target name="download_dlls" description="Download all required dlls to project main directory (Windows only)" if="is_windows">
		<if>
			<not>
				<isset property="arch"/>
			</not>
			<then>
				<input message="Choose architecture:"
					validargs="x86,x64"
					defaultvalue="x64"
					addproperty="arch"/>
				<echo>Arch: ${arch}</echo>
			</then>
		</if>
		
		<if>
			<equals arg1="${arch}" arg2="x86"/>
			<then>
				<property name="dest_dir" value="${build_x86_dir}" />
			</then>
		</if>
		<if>
			<equals arg1="${arch}" arg2="x64"/>
			<then>
				<property name="dest_dir" value="${build_x64_dir}" />
			</then>
		</if>
		<echo>dest_dir=${dest_dir}</echo>
		
		<tempfile property="temp.zip" suffix=".zip" prefix="autoscreenshot_dlls_" deleteonexit="true" destDir="${java.io.tmpdir}" />
		<echo>Temp dir: ${temp.zip}</echo>
		
		<!-- SQLite -->
		<!-- https://sqlite.org/download.html -->
		<get src="https://sqlite.org/2026/sqlite-dll-win-${arch}-3530400.zip" dest="${temp.zip}" verbose="true"/>
		<unzip src="${temp.zip}" dest="${dest_dir}">
			<patternset>
				<include name="/sqlite3.dll"/>
			</patternset>
		</unzip>
		
		<!-- OpenSSL -->
		<if>
			<equals arg1="${arch}" arg2="x86" />
			<then>
				<var name="a" value="i386-win32"/>
			</then>
		</if>
		<if>
			<equals arg1="${arch}" arg2="x64" />
			<then>
				<var name="a" value="x64_86-win64"/>
			</then>
		</if>
		<get src="https://api.github.com/repos/IndySockets/OpenSSL-Binaries/contents/Archive/openssl-1.0.2j-${a}.zip" dest="${temp.zip}" verbose="true">
			<header name="Accept" value="application/vnd.github.v3.raw" />
			<!--<header name="Authorization" value="token ${github_api_token}" />-->
		</get>
		<!--<get src="https://github.com/IndySockets/OpenSSL-Binaries/raw/refs/heads/master/openssl-1.0.2u-${a}.zip" dest="${temp.zip}" verbose="true"/>-->
		<unzip src="${temp.zip}" dest="${dest_dir}">
			<patternset>
				<include name="/ssleay32.dll"/>
				<include name="/libeay32.dll"/>
			</patternset>
		</unzip>
		
		<!-- WebP -->
		<if>
			<equals arg1="${arch}" arg2="x86" />
			<then>
				<var name="a" value="32"/>
			</then>
		</if>
		<if>
			<equals arg1="${arch}" arg2="x64" />
			<then>
				<var name="a" value="64"/>
			</then>
		</if>
		
		<get src="https://api.github.com/repos/bgrabitmap/webp/contents/bgrawebp/libwebp${a}.dll" dest="${dest_dir}" verbose="true">
			<header name="Accept" value="application/vnd.github.v3.raw" />
			<!--<header name="Authorization" value="token ${github_api_token}" />-->
		</get>
		
		<!-- AVIF -->
		<!-- https://github.com/bgrabitmap/bgrabitmap/tree/master?tab=readme-ov-file -->
		<if>
			<equals arg1="${arch}" arg2="x86" />
			<then>
				<var name="a" value="32"/>
			</then>
		</if>
		<if>
			<equals arg1="${arch}" arg2="x64" />
			<then>
				<var name="a" value="64"/>
			</then>
		</if>
		<get src="https://github.com/bgrabitmap/bgrabitmap/files/12566323/libavif_windows_dlls_ver_1_0_1-1.zip" dest="${temp.zip}" verbose="true">
			<!--<header name="Authorization" value="token ${github_api_token}" />-->
		</get>
		<unzip src="${temp.zip}" dest="${dest_dir}">
			<patternset>
				<!--<include name="/windows${a}bits/*.dll"/>-->
				
				<include name="/windows${a}bits/rav1e.dll"/>
				<include name="/windows${a}bits/libwinpthread-1.dll"/>
				<include name="/windows${a}bits/libgcc_s_*.dll"/><!-- libgcc_s_seh-1.dll / libgcc_s_dw2-1.dll -->
				<include name="/windows${a}bits/libdav1d.dll"/>
				<include name="/windows${a}bits/libavif.dll"/>
				<include name="/windows${a}bits/libaom.dll"/>
				<include name="/windows${a}bits/libjpeg-8.dll" />
				<include name="/windows${a}bits/libsharpyuv-0.dll" />	<!-- только 64бита -->
				<include name="/windows${a}bits/libstdc++-6.dll" />
				<include name="/windows${a}bits/libSvtAv1Dec.dll" />	<!-- только 64бита -->
				<include name="/windows${a}bits/libSvtAv1Enc.dll" />	<!-- только 64бита -->
				<include name="/windows${a}bits/libyuv.dll" />
			</patternset>
			<cutdirsmapper dirs="1" />
		</unzip>
	</target>
	
	<!--<target name="validate_dll_checksums">
		<!-\- todo -\->
	</target>-->
	
	<target name="copy_dlls_to_proj_root" depends="download_dlls_once">
		<echo>Copy DLLs for arch=${arch}</echo>
		<if>
			<equals arg1="${arch}" arg2="x86" />
			<then>
				<var name="src_dir" value="${build_x86_dir}"/>
			</then>
		</if>
		<if>
			<equals arg1="${arch}" arg2="x64" />
			<then>
				<var name="src_dir" value="${build_x64_dir}"/>
			</then>
		</if>
		
		<copy todir="${basedir}" verbose="true">
			<fileset dir="${src_dir}">
				<include name="*.dll"/>
			</fileset>
		</copy>
	</target>
</project>
