; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName      "Auto Screenshot"
#define MyAppExeName   "AutoScreenshot.exe"
#define MyAppVersion    GetFileProductVersion("AutoScreenshot.exe")
#ifndef MyAppRevision 
  #define MyAppRevision   'v' + MyAppVersion  ; Normally passed from command line on build process
#endif
#define MyAppPublisher "Artem Demin"
#define MyAppURL       "https://artem78.github.io/AutoScreenshot/"
#define CurrentYear    GetDateTimeString('yyyy','','')
#define X86Dir         "build\x86_files"
#define X64Dir         "build\x64_files"
#define ProgramConfigDir /*"{userappdata}\AutoScreenshot"*/ "{localappdata}\AutoScreenshot" ; NOTE:  "AutoScreenshot" must be writen WITHOUT space!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)

AppId={{E91D6BA8-641A-49F1-B724-A61B934F6522}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}

AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

SetupIconFile=AutoScreenshot.ico

AppCopyright={#CurrentYear} {#MyAppPublisher}

VersionInfoDescription={#MyAppName} installer
VersionInfoProductName={#MyAppName}
VersionInfoVersion={#MyAppVersion}

UninstallDisplayName={#MyAppName} {#MyAppVersion}
UninstallDisplayIcon={app}\{#MyAppExeName}
AppPublisher={#MyAppPublisher}

ShowLanguageDialog=yes
UsePreviousLanguage=no
LanguageDetectionMethod=uilanguage

DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=LICENSE.rtf
; OutputDir=build\setup
OutputDir=build\releases\{#MyAppRevision}
OutputBaseFilename=AutoScreenshot_{#MyAppRevision}_Windows_setup
Compression=lzma
SolidCompression=yes

; "ArchitecturesInstallIn64BitMode=x64" requests that the install be
; done in "64-bit mode" on x64, meaning it should use the native
; 64-bit Program Files directory and the 64-bit view of the registry.
; On all other architectures it will install in "32-bit mode".
ArchitecturesInstallIn64BitMode=x64
; Note: We don't set ProcessorsAllowed because we want this
; installation to run on all architectures (including Itanium,
; since it's capable of running 32-bit code too).

[Languages]
Name: "english";   MessagesFile: "compiler:Default.isl"
Name: "french";    MessagesFile: "compiler:Languages\French.isl"
Name: "german";    MessagesFile: "compiler:Languages\German.isl"
Name: "italian";   MessagesFile: "compiler:Languages\Italian.isl"
Name: "spanish";   MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish";   MessagesFile: "compiler:Languages\Turkish.isl"
Name: "russian";   MessagesFile: "compiler:Languages\Russian.isl"
Name: "Ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Install MyProg-x64.exe if running in 64-bit mode (x64; see above),
; MyProg.exe otherwise.

; Place all x64 files here
Source: "{#X64Dir}\AutoScreenshot.exe";  DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libssl-1_1-x64.dll";  DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libcrypto-1_1-x64.dll"; DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\sqlite3.dll";         DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libwebp64.dll";       DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libgcc_s_seh-1.dll";  DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libaom.dll";          DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libavif.dll";         DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libdav1d.dll";        DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;
Source: "{#X64Dir}\rav1e.dll";           DestDir: "{app}"; Flags: ignoreversion; Check: Is64BitInstallMode;

; Place all x86 files here, first one should be marked 'solidbreak'
Source: "{#X86Dir}\AutoScreenshot.exe";  DestDir: "{app}"; Flags: ignoreversion solidbreak; Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libssl-1_1.dll";      DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libcrypto-1_1.dll";   DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\sqlite3.dll";         DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libwebp32.dll";       DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libgcc_s_dw2-1.dll";  DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libaom.dll";          DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libavif.dll";         DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libdav1d.dll";        DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;
Source: "{#X86Dir}\rav1e.dll";           DestDir: "{app}"; Flags: ignoreversion;            Check: not Is64BitInstallMode;

; Place all common files here, first one should be marked 'solidbreak'
Source: "lang\*.ini";   DestDir: "{app}\lang";   Flags: ignoreversion recursesubdirs createallsubdirs solidbreak; Excludes: "*.bak"
Source: "sounds\*.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
; Remove autorun
Root: "HKCU"; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueName: "Auto Screenshot"; Flags: uninsdeletekey

[UninstallDelete]
; Remove all data files (config.ini, journal.dat, log and etc.)
; TODO: how to delete such files for ALL users?
; TODO: ask user delete all config files or not?
Name: "{#ProgramConfigDir}\*.*"; Type: files
Name: "{#ProgramConfigDir}"; Type: filesandordirs;
